### PR TITLE
feat: add signal to func

### PR DESCRIPTION
**Pull request by ronag**
Fixes: https://github.com/mcollina/hwp/issues/6

### CODE REVIEW

**Review by mcollina — COMMENTED** [review]
Would it make sense to also support the abort controller as an input?

**Comment by ronag** [comment]
> Would it make sense to also support the abort controller as an input?

Not sure I follow?

**Comment by mcollina** [comment]
Never mind! Could you add it this to the README?

**Comment by ronag** [comment]
done

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
